name: 🚀 Deploy to Production

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Importante: scarica tutta la history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build project
        run: npm run build

      - name: Prepare for deploy
        run: |
          # ELIMINA TUTTO tranne .git
          find . -maxdepth 1 ! -name '.' ! -name '.git' -exec rm -rf {} +
          
          # Copia i file di build
          cp -r dist/* .
          
          # ELIMINA la cartella .history se esiste
          rm -rf .history 2>/dev/null || true
          
          # ELIMINA la cartella dist
          rm -rf dist

      - name: Force add ALL files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add --all --force
          git status  # Per debug

      - name: Commit and push
        run: |
          git commit -m "🚀 Deploy completo: $(date +'%Y-%m-%d %H:%M:%S')" --allow-empty
          git push origin main --force